name: Godot PR Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          wget https://github.com/godotengine/godot-builds/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
      
      - run: |
          unzip Godot_v4.2.2-stable_linux.x86_64.zip
      
      - run: |
          mkdir godot
      
      - run: |
          mv Godot_v4.2.2-stable_linux.x86_64 godot

      - run: chmod +x godot/Godot_v4.2.2-stable_linux.x86_64

      - name: Test
        run: |
          ./godot/Godot_v4.2.2-stable_linux.x86_64 --headless --path . --quit-after 1
