name: Godot PR Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.2/mono/Godot_v4.2.2-stable_mono_linux_headless_x86_64.zip
          unzip Godot_v4.2.2-stable_mono_linux_headless_x86_64.zip
          mv Godot_v4.2.2-stable_mono_linux_headless_x86_64 godot

      - run: chmod +x godot/Godot_v4.2.2-stable_mono_linux_headless_x86_64

      - name: Test
        run: |
          ./godot/Godot_v4.2.2-stable_mono_linux_headless_x86_64 --headless --path . --quit-after 1
